const bingLangMap = {
  auto: 'auto-detect',
  zh: 'zh-Hans',
  en: 'en',
  ja: 'ja',
  ko: 'ko',
  fr: 'fr',
  de: 'de',
  es: 'es',
  pt: 'pt',
  ru: 'ru',
  ar: 'ar',
  it: 'it',
  th: 'th',
  vi: 'vi',
  id: 'id',
  ms: 'ms',
  tr: 'tr',
  nl: 'nl',
  pl: 'pl',
  sv: 'sv',
  da: 'da',
  fi: 'fi',
  nb: 'nb',
  cs: 'cs',
  el: 'el',
  he: 'he',
  hi: 'hi',
  bn: 'bn',
  uk: 'uk',
  ro: 'ro',
  hu: 'hu',
  sk: 'sk',
  bg: 'bg',
  hr: 'hr',
  lt: 'lt',
  lv: 'lv',
  et: 'et',
  sl: 'sl',
}

export function toBingLang(lang) {
  return bingLangMap[lang] || 'auto-detect'
}

// Bing TTS voice mapping (BCP-47 lang + voice name)
export const bingVoiceMap = {
  zh: {lang: 'zh-CN', voice: 'zh-CN-XiaoxiaoNeural'},
  en: {lang: 'en-US', voice: 'en-US-JennyNeural'},
  ja: {lang: 'ja-JP', voice: 'ja-JP-NanamiNeural'},
  ko: {lang: 'ko-KR', voice: 'ko-KR-SunHiNeural'},
  fr: {lang: 'fr-FR', voice: 'fr-FR-DeniseNeural'},
  de: {lang: 'de-DE', voice: 'de-DE-KatjaNeural'},
  es: {lang: 'es-ES', voice: 'es-ES-ElviraNeural'},
  pt: {lang: 'pt-PT', voice: 'pt-PT-RaquelNeural'},
  it: {lang: 'it-IT', voice: 'it-IT-ElsaNeural'},
  ru: {lang: 'ru-RU', voice: 'ru-RU-SvetlanaNeural'},
  ar: {lang: 'ar-EG', voice: 'ar-EG-SalmaNeural'},
  sv: {lang: 'sv-SE', voice: 'sv-SE-HedvigNeural'},
  ro: {lang: 'ro-RO', voice: 'ro-RO-AlinaNeural'},
  th: {lang: 'th-TH', voice: 'th-TH-PremwadeeNeural'},
  sk: {lang: 'sk-SK', voice: 'sk-SK-ViktoriaNeural'},
  nl: {lang: 'nl-NL', voice: 'nl-NL-ColetteNeural'},
  cs: {lang: 'cs-CZ', voice: 'cs-CZ-AntoninNeural'},
  tr: {lang: 'tr-TR', voice: 'tr-TR-EmelNeural'},
  el: {lang: 'el-GR', voice: 'el-GR-AthinaNeural'},
  da: {lang: 'da-DK', voice: 'da-DK-ChristelNeural'},
  fi: {lang: 'fi-FI', voice: 'fi-FI-NooraNeural'},
  pl: {lang: 'pl-PL', voice: 'pl-PL-AgnieszkaNeural'},
  nb: {lang: 'nb-NO', voice: 'nb-NO-PernilleNeural'},
  lt: {lang: 'lt-LT', voice: 'lt-LT-OnaNeural'},
  lv: {lang: 'lv-LV', voice: 'lv-LV-EveritaNeural'},
  uk: {lang: 'uk-UA', voice: 'uk-UA-OstapNeural'},
  bg: {lang: 'bg-BG', voice: 'bg-BG-KalinaNeural'},
  id: {lang: 'id-ID', voice: 'id-ID-DamayantiNeural'},
  ms: {lang: 'ms-MY', voice: 'ms-MY-OsmanNeural'},
  sl: {lang: 'sl-SI', voice: 'sl-SI-PetraNeural'},
  et: {lang: 'et-EE', voice: 'et-EE-AnuNeural'},
  vi: {lang: 'vi-VN', voice: 'vi-VN-HoaiMyNeural'},
  he: {lang: 'he-IL', voice: 'he-IL-HilaNeural'},
  hi: {lang: 'hi-IN', voice: 'hi-IN-MadhurNeural'},
  bn: {lang: 'bn-IN', voice: 'bn-IN-AnuNeural'},
  hr: {lang: 'hr-HR', voice: 'hr-HR-SreckoNeural'},
}
