export const LANGUAGES = [
  {code: 'auto', name: '自动检测', flag: '🌐'},
  {code: 'zh', name: '中文', flag: '🇨🇳'},
  {code: 'en', name: '英文', flag: '🇺🇸'},
  {code: 'ja', name: '日文', flag: '🇯🇵'},
  {code: 'ko', name: '韩文', flag: '🇰🇷'},
  {code: 'fr', name: '法文', flag: '🇫🇷'},
  {code: 'de', name: '德文', flag: '🇩🇪'},
  {code: 'es', name: '西班牙文', flag: '🇪🇸'},
  {code: 'pt', name: '葡萄牙文', flag: '🇵🇹'},
  {code: 'ru', name: '俄文', flag: '🇷🇺'},
  {code: 'ar', name: '阿拉伯文', flag: '🇸🇦'},
  {code: 'it', name: '意大利文', flag: '🇮🇹'},
  {code: 'th', name: '泰文', flag: '🇹🇭'},
  {code: 'vi', name: '越南文', flag: '🇻🇳'},
  {code: 'id', name: '印尼文', flag: '🇮🇩'},
  {code: 'ms', name: '马来文', flag: '🇲🇾'},
  {code: 'tr', name: '土耳其文', flag: '🇹🇷'},
  {code: 'nl', name: '荷兰文', flag: '🇳🇱'},
  {code: 'pl', name: '波兰文', flag: '🇵🇱'},
  {code: 'sv', name: '瑞典文', flag: '🇸🇪'},
  {code: 'da', name: '丹麦文', flag: '🇩🇰'},
  {code: 'fi', name: '芬兰文', flag: '🇫🇮'},
  {code: 'nb', name: '挪威文', flag: '🇳🇴'},
  {code: 'cs', name: '捷克文', flag: '🇨🇿'},
  {code: 'el', name: '希腊文', flag: '🇬🇷'},
  {code: 'he', name: '希伯来文', flag: '🇮🇱'},
  {code: 'hi', name: '印地文', flag: '🇮🇳'},
  {code: 'bn', name: '孟加拉文', flag: '🇧🇩'},
  {code: 'uk', name: '乌克兰文', flag: '🇺🇦'},
  {code: 'ro', name: '罗马尼亚文', flag: '🇷🇴'},
  {code: 'hu', name: '匈牙利文', flag: '🇭🇺'},
  {code: 'sk', name: '斯洛伐克文', flag: '🇸🇰'},
  {code: 'bg', name: '保加利亚文', flag: '🇧🇬'},
  {code: 'hr', name: '克罗地亚文', flag: '🇭🇷'},
  {code: 'lt', name: '立陶宛文', flag: '🇱🇹'},
  {code: 'lv', name: '拉脱维亚文', flag: '🇱🇻'},
  {code: 'et', name: '爱沙尼亚文', flag: '🇪🇪'},
  {code: 'sl', name: '斯洛文尼亚文', flag: '🇸🇮'},
]

export function getLangName(code) {
  const lang = LANGUAGES.find(l => l.code === code)
  return lang ? lang.name : code
}
