// 百度翻译语言代码映射
export const baiduLangMap = {
  'auto': 'auto',
  'zh': 'zh',
  'zh-tw': 'cht',
  'wyw': 'wyw',
  'en': 'en',
  'ja': 'jp',
  'ko': 'kor',
  'fr': 'fra',
  'es': 'spa',
  'pt': 'pt',
  'it': 'it',
  'de': 'de',
  'ru': 'ru',
  'ar': 'ara',
  'sv': 'swe',
  'ro': 'rom',
  'th': 'th',
  'sk': 'slo',
  'nl': 'nl',
  'hu': 'hu',
  'el': 'el',
  'da': 'dan',
  'fi': 'fin',
  'pl': 'pl',
  'cs': 'cs',
  'tr': 'tr',
  'lt': 'lit',
  'lv': 'lav',
  'uk': 'ukr',
  'bg': 'bul',
  'id': 'id',
  'ms': 'msa',
  'sl': 'slv',
  'et': 'est',
  'vi': 'vie',
  'fa': 'per',
  'hi': 'hin',
  'te': 'tel',
  'ta': 'tam',
  'ur': 'urd',
  'fil': 'fil',
  'km': 'khm',
  'lo': 'lo',
  'bn': 'ben',
  'my': 'bur',
  'no': 'nor',
  'sr': 'srp',
  'hr': 'hrv',
  'mn': 'mon',
  'he': 'heb',
  'ka': 'geo',
}

export function toBaiduLang(lang) {
  return baiduLangMap[lang] || 'auto'
}
